<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::pluck('id', 'name');

        $products = [
        [
            'category' => 'Minuman',
            'code' => 'PRD-00111111',
            'barcode' => '899100000001',
            'name' => 'Air Mineral 600ml',
            'purchase_price' => 2500,
            'selling_price' => 4000,
            'stock' => 100,
            'minimum_stock' => 20,
            'unit' => 'botol',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-002',
            'barcode' => '8991000000022222222',
            'name' => 'Teh Botol',
            'purchase_price' => 3500,
            'selling_price' => 5000,
            'stock' => 80,
            'minimum_stock' => 15,
            'unit' => 'botol',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-003',
            'barcode' => '899100000003333333333',
            'name' => 'Teh Pucuk Harum',
            'purchase_price' => 3000,
            'selling_price' => 5000,
            'stock' => 100,
            'minimum_stock' => 20,
            'unit' => 'botol',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-004',
            'barcode' => '8991000000044435',
            'name' => 'Kopi Susu',
            'purchase_price' => 5000,
            'selling_price' => 8000,
            'stock' => 50,
            'minimum_stock' => 10,
            'unit' => 'gelas',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-005',
            'barcode' => '8991000000055555',
            'name' => 'Es Teh Manis',
            'purchase_price' => 2500,
            'selling_price' => 5000,
            'stock' => 50,
            'minimum_stock' => 10,
            'unit' => 'gelas',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-006',
            'barcode' => '89910000000644',
            'name' => 'Jus Jeruk',
            'purchase_price' => 5000,
            'selling_price' => 10000,
            'stock' => 40,
            'minimum_stock' => 10,
            'unit' => 'gelas',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-007',
            'barcode' => '899100000007443',
            'name' => 'Susu Coklat',
            'purchase_price' => 5000,
            'selling_price' => 8000,
            'stock' => 40,
            'minimum_stock' => 10,
            'unit' => 'botol',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-008',
            'barcode' => '899100000008232',
            'name' => 'Es Jeruk',
            'purchase_price' => 3000,
            'selling_price' => 7000,
            'stock' => 50,
            'minimum_stock' => 10,
            'unit' => 'gelas',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-009',
            'barcode' => '89910000000923',
            'name' => 'Kopi Hitam',
            'purchase_price' => 3000,
            'selling_price' => 6000,
            'stock' => 50,
            'minimum_stock' => 10,
            'unit' => 'gelas',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Minuman',
            'code' => 'PRD-010',
            'barcode' => '899100000032310',
            'name' => 'Air Mineral 1500ml',
            'purchase_price' => 4500,
            'selling_price' => 7000,
            'stock' => 60,
            'minimum_stock' => 10,
            'unit' => 'botol',
            'image' => null,
            'status' => true,
        ],

        [
            'category' => 'Makanan',
            'code' => 'PRD-011',
            'barcode' => '899100043300011',
            'name' => 'Mie Instan Goreng',
            'purchase_price' => 2500,
            'selling_price' => 3500,
            'stock' => 100,
            'minimum_stock' => 20,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-012',
            'barcode' => '899104340000012',
            'name' => 'Mie Instan Kuah',
            'purchase_price' => 2500,
            'selling_price' => 3500,
            'stock' => 100,
            'minimum_stock' => 20,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-013',
            'barcode' => '89910434230000013',
            'name' => 'Nasi Goreng',
            'purchase_price' => 8000,
            'selling_price' => 15000,
            'stock' => 30,
            'minimum_stock' => 5,
            'unit' => 'porsi',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-014',
            'barcode' => '899102320000014',
            'name' => 'Mie Goreng',
            'purchase_price' => 7000,
            'selling_price' => 12000,
            'stock' => 30,
            'minimum_stock' => 5,
            'unit' => 'porsi',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-015',
            'barcode' => '899103230000015',
            'name' => 'Ayam Goreng',
            'purchase_price' => 9000,
            'selling_price' => 15000,
            'stock' => 40,
            'minimum_stock' => 10,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-016',
            'barcode' => '899100323000016',
            'name' => 'Nasi Ayam',
            'purchase_price' => 10000,
            'selling_price' => 18000,
            'stock' => 30,
            'minimum_stock' => 5,
            'unit' => 'porsi',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-017',
            'barcode' => '8991003232000017',
            'name' => 'Roti Coklat',
            'purchase_price' => 3000,
            'selling_price' => 5000,
            'stock' => 60,
            'minimum_stock' => 10,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-018',
            'barcode' => '8991323200000018',
            'name' => 'Roti Keju',
            'purchase_price' => 3500,
            'selling_price' => 6000,
            'stock' => 60,
            'minimum_stock' => 10,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-019',
            'barcode' => '8991323200000019',
            'name' => 'Biskuit Coklat',
            'purchase_price' => 7000,
            'selling_price' => 10000,
            'stock' => 50,
            'minimum_stock' => 10,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-020323',
            'barcode' => '8991032320000020',
            'name' => 'Keripik Singkong',
            'purchase_price' => 5000,
            'selling_price' => 8000,
            'stock' => 70,
            'minimum_stock' => 15,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-023222231',
            'barcode' => '89932100000021',
            'name' => 'Keripik Kentang',
            'purchase_price' => 6000,
            'selling_price' => 10000,
            'stock' => 60,
            'minimum_stock' => 15,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-02322222',
            'barcode' => '899323100000022',
            'name' => 'Sosis Bakar',
            'purchase_price' => 5000,
            'selling_price' => 8000,
            'stock' => 50,
            'minimum_stock' => 10,
            'unit' => 'pcs',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-02223222',
            'barcode' => '899132300000023',
            'name' => 'Bakso Bakar',
            'purchase_price' => 5000,
            'selling_price' => 8000,
            'stock' => 50,
            'minimum_stock' => 10,
            'unit' => 'porsi',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-024',
            'barcode' => '899100000024',
            'name' => 'Kentang Goreng',
            'purchase_price' => 7000,
            'selling_price' => 12000,
            'stock' => 40,
            'minimum_stock' => 10,
            'unit' => 'porsi',
            'image' => null,
            'status' => true,
        ],
        [
            'category' => 'Makanan',
            'code' => 'PRD-025',
            'barcode' => '899100000025',
            'name' => 'Pisang Goreng',
            'purchase_price' => 4000,
            'selling_price' => 8000,
            'stock' => 50,
            'minimum_stock' => 10,
            'unit' => 'porsi',
            'image' => null,
            'status' => true,
        ],
    ];

        foreach ($products as $product) {
            $categoryId = $categories[$product['category']] ?? null;

            if (!$categoryId) {
                continue;
            }

            Product::create([
                'category_id' => $categoryId,
                'code' => $product['code'],
                'barcode' => $product['barcode'],
                'name' => $product['name'],
                'purchase_price' => $product['purchase_price'],
                'selling_price' => $product['selling_price'],
                'stock' => $product['stock'],
                'minimum_stock' => $product['minimum_stock'],
                'unit' => $product['unit'],
                'image' => $product['image'],
                'status' => $product['status'],
            ]);
        }
    }
}
